Implement fixes proposed by Phoebe for ROOT v6.16.00.
umd-lhcb/root pull request #1
Opened 2022-12-01 13:15 UTC by yipengsun

Part of umd-lhcb/root-curated#12.

2022-12-01 16:13 UTC, CoffeeIntoScience requested changes
See the inline comment. To recapitulate them here to maybe have things more compact

- moving the i increment up before you do the interpcode lookup means you need to start from -1 so your first lookup is i=0

- the evaluate method needs the same changes to the i counter

- removing the one method from this file requires removing the corresponding prototype from the header as well

2022-12-01 16:13 UTC, CoffeeIntoScience commented on roofit/histfactory/src/PiecewiseInterpolation.cxx
> +      ++i;
if we increment here and `i` starts from zero we are always looking at the wrong `alpha`'s interp code

2022-12-01 16:13 UTC, CoffeeIntoScience commented on roofit/histfactory/src/PiecewiseInterpolation.cxx
> +      ++i;
Please change line 215 to `int i=-1;`

2022-12-01 16:13 UTC, CoffeeIntoScience commented on roofit/histfactory/src/PiecewiseInterpolation.cxx
> +      ++i;
The same changes are needed in `PiecewiseInterpolation::evaluate()` (same bug exists there). See lines 383 - 396

2022-12-01 16:13 UTC, CoffeeIntoScience commented on roofit/histfactory/src/PiecewiseInterpolation.cxx
> -Int_t PiecewiseInterpolation::getAnalyticalIntegralWN(RooArgSet& allVars, RooArgSet& analVars,
This requires also removing the function prototype from the header file

2022-12-01 21:21 UTC, yipengsun commented
Done! Also made sure that my editor is not removing trailing whitespaces so the diff is minimal.

2022-12-02 19:48 UTC, CoffeeIntoScience approved these changes
looks perfect!

2022-12-02 19:50 UTC, merged